# Objective
- Identify which step has significant downtime spread and thus to prioritize root cause analysis

## Benefit

By optimizing the process which shows significant spread, companies can:
- Improve consistency of production throughput
- Enable next stage of optimization to reduce the downtime of each production
- Minimize process overruns

## Data Ingestion

In [1]:
import pandas as pd

df_downtimes = pd.read_excel(r"data\process_step_downtime.xlsx")
df_downtimes

    batch  Step 1  Step 2  Step 3  Step 4  Step 5
0       1       5      34     312      19      13
1       2       4      15     309      20       8
2       3       5      11     311      19       6
3       4       3      23     307      15      13
4       5       3      20     302      19      14
5       6       5      30     307      18      14
6       7       5      35     310      18      14
7       8       6      30     306      19      10
8       9       4      30     310      16       6
9      10       4      30     310      16      11
10     11       5      34     315      20      14
11     12       5      34     306      18       7
12     13       4      21     304      17      13
13     14       3      20     301      20      14
14     15       5      34     309      17       8
15     16       5      19     314      16      10
16     17       2      34     311      17       9
17     18       4      15     304      19      10
18     19       3      24     306      17       9
19     20       5      25     308      16      12
20     21       5      12     308      19       9
21     22       5      38     312      17      15
22     23       4      40     303      18      13
23     24       5      36     310      16      14
24     25       4      32     312      16      11
25     26       4      32     311      19      15
26     27       3      39     307      16      10
27     28       4      26     312      20      14
28     29       5      19     310      20      13
29     30       4      24     300      19       8

## Downtime Spread Analysis

In [2]:
df_downtimes.drop(columns=["batch"], inplace=True)
df_downtimes

    Step 1  Step 2  Step 3  Step 4  Step 5
0        5      34     312      19      13
1        4      15     309      20       8
2        5      11     311      19       6
3        3      23     307      15      13
4        3      20     302      19      14
5        5      30     307      18      14
6        5      35     310      18      14
7        6      30     306      19      10
8        4      30     310      16       6
9        4      30     310      16      11
10       5      34     315      20      14
11       5      34     306      18       7
12       4      21     304      17      13
13       3      20     301      20      14
14       5      34     309      17       8
15       5      19     314      16      10
16       2      34     311      17       9
17       4      15     304      19      10
18       3      24     306      17       9
19       5      25     308      16      12
20       5      12     308      19       9
21       5      38     312      17      15
22       4      40     303      18      13
23       5      36     310      16      14
24       4      32     312      16      11
25       4      32     311      19      15
26       3      39     307      16      10
27       4      26     312      20      14
28       5      19     310      20      13
29       4      24     300      19       8

In [3]:
df_downtimes.describe()

          Step 1     Step 2      Step 3     Step 4     Step 5
count  30.000000  30.000000   30.000000  30.000000  30.000000
mean    4.266667  27.200000  308.233333  17.866667  11.233333
std     0.907187   8.260417    3.793673   1.547709   2.775302
min     2.000000  11.000000  300.000000  15.000000   6.000000
25%     4.000000  20.250000  306.000000  16.250000   9.000000
50%     4.000000  30.000000  309.000000  18.000000  11.500000
75%     5.000000  34.000000  311.000000  19.000000  14.000000
max     6.000000  40.000000  315.000000  20.000000  15.000000